---
- hosts: debian
  user: root

  tasks:

    - name: debian update
      action: apt update_cache=yes

    - name: uninstall vmware tools
      command: /etc/vmware-tools/installer.sh uninstall

    - name: apt install open-vm-tools
      action: apt name={{ item }} state=present
      with_items:
      - open-vm-tools

#    - name: reboot
#      command: /sbin/reboot
