---

## run on icinga2 master
- hosts: icinga2-master-server.localdomain.tld

  tasks:

  ## it is important that first we generate new ticket for the icinga client on master
  - name: generate ticket on the icinga master and save it as a variable
    shell: /usr/lib64/icinga2/sbin/icinga2 pki ticket --cn {{ hostitem }}
    register: ticket

## run on icinga2 client host comes from parameter...
- hosts: "{{ hostitem }}"

  vars:
    ## icinga basics
    # replace all icinga2-master-server.localdomain.tld with your own
    # replace rhn_user and rhn_password with your own
    master_hostname: icinga2-master-server.localdomain.tld
    master_ip: "{{ hostvars['icinga2-master-server.localdomain.tld']['ansible_default_ipv4']['address'] }}"
    master_port: 5665

    ## rhn (RHN, Satellite, Spacewalk Credentials)
    rhn_user: YourUserName
    rhn_password: YourPassword
    rhn_channel: icinga-epel-7

  tasks:

  ## prepare icinga setup
  - name: check if repo|rhn channel is already there
    shell: rhn-channel -l | grep -Fxq "{{ rhn_channel }}" 
    register: rhn_status
    ignore_errors: True
    changed_when: False
    tags:
      - rhn-check

  - name: add rhn icinga-epel-7 channel
    command: /usr/sbin/rhn-channel -a -c "{{ rhn_channel }}" -u "{{ rhn_user }}" -p "{{rhn_password}}"
    when: rhn_status.rc == 1
    tags:
      - rhn-check

  ## install icinga2 packages
  - name: install icinga packages
    yum: name={{ item }} state=present disable_gpg_check=yes
    with_items:
      - icinga2 
      - icinga2-bin
      - icinga2-common
      
  ## prepare pki on client side
  - name: create pki folder
    file: path=/etc/icinga2/pki state=directory mode=0700 owner=icinga group=icinga

  - name: create cert
    shell: icinga2 pki new-cert --cn {{ hostitem }} --key /etc/icinga2/pki/{{ hostitem }}.key --cert /etc/icinga2/pki/{{ hostitem }}.crt

  - name: save the masters cert as trustedcert
    shell: icinga2 pki save-cert --key /etc/icinga2/pki/{{ hostitem }}.key --cert /etc/icinga2/pki/{{ hostitem }}.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --host {{ master_hostname }}

  - name: request the certificate from the icinga server
    shell: "icinga2 pki request --host {{ master_hostname }} --port {{ master_port }} --ticket {{ hostvars['icinga2-master-server.localdomain.tld']['ticket']['stdout'] }} --key /etc/icinga2/pki/{{ hostitem }}.key --cert /etc/icinga2/pki/{{ hostitem }}.crt --trustedcert /etc/icinga2/pki/trusted-master.crt --ca /etc/icinga2/pki/ca.key"

  - name: node setup
    shell: "icinga2 node setup --ticket {{ hostvars['hcm2icinga.sharedtcs.net']['ticket']['stdout'] }} --endpoint {{ master_hostname }} --zone {{ hostitem }} --master_host {{ master_hostname }} --trustedcert /etc/icinga2/pki/trusted-master.crt --cn {{ hostitem }}"

  ## enabled and start incinga2 service on client side
  - name: icinga service enabled and start
    systemd:
      name: icinga2
      state: restarted
      enabled: yes
    tags:
      - icinga2-restart 

## run on icinga2 master
- hosts: icinga2-master-server.localdomain.tld 

  vars:
    client_port: 5665

  tasks:

  - name: add host
    shell: icinga2 node add {{ hostitem }}

  - name: set host ip
    shell: icinga2 node set {{ hostitem }} --host {{ hostitem }} --port {{ client_port }}

  - name: copy host definition to icinga master
    template: src=templates/icinga_hosts_def.j2
      dest=/etc/icinga/servers/myservergroup.cfg
      owner=root
      group=root
      mode=0644
    notify:
    - restart icinga2
